In [56]:
import numpy as np

rewards = np.arange(4, 10)

T = len(rewards)
idx = np.arange(0, T)
gamma = 0.9
discounts = gamma ** idx
disc_matrix = np.zeros((T,T))

print(disc_matrix, discounts)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] [1.      0.9     0.81    0.729   0.6561  0.59049]


In [24]:
disc_matrix = np.tril(disc_matrix)
print(disc_matrix)

[[1.      0.      0.      0.      0.      0.     ]
 [0.9     0.9     0.      0.      0.      0.     ]
 [0.81    0.81    0.81    0.      0.      0.     ]
 [0.729   0.729   0.729   0.729   0.      0.     ]
 [0.6561  0.6561  0.6561  0.6561  0.6561  0.     ]
 [0.59049 0.59049 0.59049 0.59049 0.59049 0.59049]]


In [57]:
for col in range(disc_matrix.shape[1]):
    print(discounts[:-col-1])
    print(disc_matrix[col:, col])
    disc_matrix[col:, col] = discounts[:-col] if col != 0 else discounts
print(disc_matrix)

[1.     0.9    0.81   0.729  0.6561]
[0. 0. 0. 0. 0. 0.]
[1.    0.9   0.81  0.729]
[0. 0. 0. 0. 0.]
[1.   0.9  0.81]
[0. 0. 0. 0.]
[1.  0.9]
[0. 0. 0.]
[1.]
[0. 0.]
[]
[0.]
[[1.      0.      0.      0.      0.      0.     ]
 [0.9     1.      0.      0.      0.      0.     ]
 [0.81    0.9     1.      0.      0.      0.     ]
 [0.729   0.81    0.9     1.      0.      0.     ]
 [0.6561  0.729   0.81    0.9     1.      0.     ]
 [0.59049 0.6561  0.729   0.81    0.9     1.     ]]


In [47]:
rewards @ disc_matrix

array([29.02621, 25.02621, 20.52621, 15.66621, 10.56321,  5.31441])